In [113]:
import glob
import os
import sys
import tempfile
from pathlib import Path
from zipfile import ZipFile

from tqdm.auto import tqdm

import polars as pl
pl.Config.set_fmt_str_lengths(100)
pl.Config.set_tbl_rows(10)

sys.path.append('../src')

## Read Iris

In [114]:
iris_path = Path('/run/media/leo/b9827f00-f8da-4458-bc94-97b28f1a0989/iris-data-2025-07-03.zip')

We read the Master and Identifier tables of the Iris dataset and we join them by the ITEM_ID. We then filter this dataframe to keep only the entries that have at least a non-null DOI, ISBN or PMID. 

We also keep only the OWNING_COLLECTION column to denote the labels of the types of the entries, because of computational efficiency

In [135]:
df_iris_master = pl.read_csv(ZipFile(iris_path).open("ODS_L1_IR_ITEM_MASTER_ALL.csv").read())
df_iris_identifier = pl.read_csv(ZipFile(iris_path).open("ODS_L1_IR_ITEM_IDENTIFIER.csv").read(), columns=['ITEM_ID', 'IDE_DOI', 'IDE_ISBN', 'IDE_PMID'], ignore_errors=True, schema_overrides={'ITEM_ID': pl.Int64, 'IDE_DOI': pl.Utf8, 'IDE_ISBN': pl.Utf8, 'IDE_PMID': pl.Utf8})
df_iris_relation = pl.read_csv(ZipFile(iris_path).open('ODS_L1_IR_ITEM_RELATION.csv').read(), columns=['ITEM_ID', 'REL_ISPARTOFBOOK', 'REL_ISPARTOFJOURNAL'], infer_schema_length=None, ignore_errors=True, schema_overrides={'ITEM_ID': pl.Int64, 'REL_ISPARTOFBOOK': pl.Utf8, 'REL_ISPARTOFJOURNAL': pl.Utf8})
df_iris_description = pl.read_csv(ZipFile(iris_path).open('ODS_L1_IR_ITEM_DESCRIPTION.csv').read(), columns=['ITEM_ID', 'DES_ALLPEOPLE', 'DES_NUMBEROFAUTHORS'])
df_iris_publisher = pl.read_csv(ZipFile(iris_path).open('ODS_L1_IR_ITEM_PUBLISHER.csv').read(), columns=['ITEM_ID', 'PUB_NAME', 'PUB_PLACE', 'PUB_COUNTRY'])


df = df_iris_identifier.join(df_iris_master, on='ITEM_ID', how='inner')#.join(df_iris_relation, on='ITEM_ID', how='inner')
#df_authors = df.join(df_iris_description, on='ITEM_ID', how='inner')



# a df where for each br at least one of the identifiers is not null
df_filtered = df.filter(pl.col('IDE_DOI').is_not_null() | pl.col('IDE_ISBN').is_not_null() | pl.col('IDE_PMID').is_not_null())[
    ['ITEM_ID', 'IDE_DOI', 'IDE_ISBN', 'IDE_PMID', 'OWNING_COLLECTION']#, 'REL_ISPARTOFBOOK', 'REL_ISPARTOFJOURNAL']
]

df_noid =  df.filter(pl.col('IDE_DOI').is_null() & pl.col('IDE_ISBN').is_null() & pl.col('IDE_PMID').is_null())
print('original len: ', df.__len__(), '| len after filtering out entities without PIDs: ', df_filtered.__len__())
df_filtered.head()

original len:  402505 | len after filtering out entities without PIDs:  263579

shape: (5, 5)
┌─────────┬────────────────────────────┬────────────────┬──────────┬───────────────────┐
│ ITEM_ID ┆ IDE_DOI                    ┆ IDE_ISBN       ┆ IDE_PMID ┆ OWNING_COLLECTION │
│ ---     ┆ ---                        ┆ ---            ┆ ---      ┆ ---               │
│ i64     ┆ str                        ┆ str            ┆ str      ┆ i64               │
╞═════════╪════════════════════════════╪════════════════╪══════════╪═══════════════════╡
│ 60479   ┆ null                       ┆ 8883125150     ┆ null     ┆ 50                │
│ 82956   ┆ null                       ┆ 88.387.3686.3; ┆ null     ┆ 57                │
│         ┆                            ┆ 88.387.3687.1  ┆          ┆                   │
│ 73478   ┆ 10.2110/palo.2005.p05-020r ┆ null           ┆ null     ┆ 35                │
│ 81464   ┆ null                       ┆  0769525881    ┆ null     ┆ 57                │
│ 77859   ┆ null                       ┆ 9788878490178  ┆ null     ┆ 57                │
└─────────┴────────────────────────────┴────────────────┴──────────┴───────────────────┘

In [116]:
metadata_df = df_iris_master.join(df_iris_relation.cast({'ITEM_ID': pl.Int64}), on='ITEM_ID').join(df_iris_description, on='ITEM_ID').join(df_iris_publisher, on='ITEM_ID')

metadata_df.head(2)

shape: (2, 12)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ ITEM_ID ┆ DATE_ISSUE ┆ TITLE     ┆ OWNING_CO ┆ … ┆ DES_NUMBE ┆ PUB_NAME  ┆ PUB_PLACE ┆ PUB_COUNT │
│ ---     ┆ D_YEAR     ┆ ---       ┆ LLECTION  ┆   ┆ ROFAUTHOR ┆ ---       ┆ ---       ┆ RY        │
│ i64     ┆ ---        ┆ str       ┆ ---       ┆   ┆ S         ┆ str       ┆ str       ┆ ---       │
│         ┆ i64        ┆           ┆ i64       ┆   ┆ ---       ┆           ┆           ┆ str       │
│         ┆            ┆           ┆           ┆   ┆ i64       ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 182786  ┆ 2013       ┆ Integrazi ┆ 41        ┆ … ┆ 1         ┆ Società   ┆ Bologna   ┆ ITA       │
│         ┆            ┆ one di    ┆           ┆   ┆           ┆ Editrice  ┆           ┆           │
│         ┆            ┆ metodi    ┆           ┆   ┆           ┆ Esculapio ┆           ┆           │
│         ┆            ┆ numerici  ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ e sperime ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ ntali:    ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ una prosp ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ ettiva    ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ biomeccan ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ ica       ┆           ┆   ┆           ┆           ┆           ┆           │
│ 182871  ┆ 2013       ┆ Periodic  ┆ 35        ┆ … ┆ 2         ┆ null      ┆ null      ┆ null      │
│         ┆            ┆ Limb      ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Movements ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ during    ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Sleep: A  ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ New Sleep ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ -Related  ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Cardiovas ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ cular     ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Risk      ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Factor?   ┆           ┆   ┆           ┆           ┆           ┆           │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

We see that 3 entries do not have a type assigned to them:

In [117]:
df_iris_master.filter(pl.col('OWNING_COLLECTION').is_null())

shape: (3, 5)
┌─────────┬──────────────────┬─────────────────────────┬───────────────────┬───────────────────────┐
│ ITEM_ID ┆ DATE_ISSUED_YEAR ┆ TITLE                   ┆ OWNING_COLLECTION ┆ OWNING_COLLECTION_DES │
│ ---     ┆ ---              ┆ ---                     ┆ ---               ┆ ---                   │
│ i64     ┆ i64              ┆ str                     ┆ i64               ┆ str                   │
╞═════════╪══════════════════╪═════════════════════════╪═══════════════════╪═══════════════════════╡
│ 813996  ┆ 2023             ┆ Rare predicted          ┆ null              ┆ null                  │
│         ┆                  ┆ loss-of-function        ┆                   ┆                       │
│         ┆                  ┆ variants of type I IFN  ┆                   ┆                       │
│         ┆                  ┆ immunity genes are      ┆                   ┆                       │
│         ┆                  ┆ associated with         ┆                   ┆                       │
│         ┆                  ┆ life-threa…             ┆                   ┆                       │
│ 843497  ┆ 2024             ┆ Quantifying             ┆ null              ┆ null                  │
│         ┆                  ┆ Generalizations:        ┆                   ┆                       │
│         ┆                  ┆ Exploring the Divide    ┆                   ┆                       │
│         ┆                  ┆ Between Human and LLMs' ┆                   ┆                       │
│         ┆                  ┆ Sensitivity to          ┆                   ┆                       │
│         ┆                  ┆ Quantificat…            ┆                   ┆                       │
│ 718686  ┆ 9999             ┆ Culture, Fashion, and   ┆ null              ┆ null                  │
│         ┆                  ┆ Society Notebook        ┆                   ┆                       │
└─────────┴──────────────────┴─────────────────────────┴───────────────────┴───────────────────────┘

## Extract the list of PIDs

We extract a list of all the PIDs for each entry of the filtered IRIS dataframe by extracting the values of the columns `IDE_DOI`, `IDE_ISBN`, and `IDE_PMID`. These ids are normalized and the rotten ones are filtered out. Finally, they are all stored in a single list that we'll use to filter the Meta dump.

In [122]:
dois = df_filtered.select('ITEM_ID', 'IDE_DOI', 'OWNING_COLLECTION').drop_nulls('IDE_DOI')

filtered_dois = (
    dois
    .with_columns(('doi:'+pl.col('IDE_DOI').str.extract(r'(10\.\d{4,}\/[^,\s;]*)').str.to_lowercase()).alias('id'))
    .drop_nulls('id')
    .drop('IDE_DOI')
    .rename({'ITEM_ID': 'iris_id'})
)

print(f'Final DOIs count: {filtered_dois.shape[0]}. Removed {dois.shape[0] - filtered_dois.shape[0]} DOIs without a valid DOI.')

Final DOIs count: 184216. Removed 238 DOIs without a valid DOI.

In [123]:
pmids = df_filtered.select('ITEM_ID', 'IDE_PMID', 'OWNING_COLLECTION').drop_nulls('IDE_PMID')

filtered_pmids = (
    pmids
    .filter(
        ~pl.col('IDE_PMID').str.contains('PMC')
        )
    .with_columns(('pmid:'+pl.col('IDE_PMID').str.extract(r'0*([1-9][0-9]{1,8})', 1).str.to_lowercase()).alias('id'))
    .drop_nulls('id')
    .drop('IDE_PMID')
    .rename({'ITEM_ID': 'iris_id'})
)

print(f'Final PMIDs count: {filtered_pmids.shape[0]}. Removed {pmids.shape[0] - filtered_pmids.shape[0]} PMIDs without a valid PMID.')

Final PMIDs count: 59978. Removed 6 PMIDs without a valid PMID.

In [124]:
isbns = df_filtered.select('ITEM_ID', 'IDE_ISBN', 'OWNING_COLLECTION').drop_nulls('IDE_ISBN')

filtered_isbns = (
    isbns
    .with_columns(
        ('isbn:'+pl.col('IDE_ISBN').str.extract_all(r'(ISBN[-]*(1[03])*[ ]*(: ){0,1})*(([0-9Xx][- ]*){13}|([0-9Xx][- ]*){10})').list.first().str.replace_all(r'[- ]', '').str.to_lowercase()).alias('id')
    )
    .drop_nulls('id')
    .drop('IDE_ISBN')
    .rename({'ITEM_ID': 'iris_id'})
)

print(f'Final ISBNs count: {filtered_isbns.shape[0]}. Removed {isbns.shape[0] - filtered_isbns.shape[0]} ISBNs without a valid ISBN.')

Final ISBNs count: 92801. Removed 974 ISBNs without a valid ISBN.

In [125]:
dois_pmids_isbns_list = pl.concat([filtered_dois, filtered_pmids, filtered_isbns]).rename({'OWNING_COLLECTION': 'iris_type'})

print('number of total PIDs:', len(dois_pmids_isbns_list))
dois_pmids_isbns_list.head()

number of total PIDs: 336995

shape: (5, 3)
┌─────────┬───────────┬──────────────────────────────────────┐
│ iris_id ┆ iris_type ┆ id                                   │
│ ---     ┆ ---       ┆ ---                                  │
│ i64     ┆ i64       ┆ str                                  │
╞═════════╪═══════════╪══════════════════════════════════════╡
│ 73478   ┆ 35        ┆ doi:10.2110/palo.2005.p05-020r       │
│ 157248  ┆ 35        ┆ doi:10.1007/jhep07(2012)133          │
│ 155300  ┆ 40        ┆ doi:10.1016/s0021-9290(12)70228-2    │
│ 156226  ┆ 35        ┆ doi:10.1016/j.compstruct.2011.10.026 │
│ 158748  ┆ 58        ┆ doi:10.1007/978-94-007-5634-2_191    │
└─────────┴───────────┴──────────────────────────────────────┘

In [126]:
dois_pmids_isbns_list.filter(pl.col('id').is_null())

shape: (0, 3)
┌─────────┬───────────┬─────┐
│ iris_id ┆ iris_type ┆ id  │
│ ---     ┆ ---       ┆ --- │
│ i64     ┆ i64       ┆ str │
╞═════════╪═══════════╪═════╡
└─────────┴───────────┴─────┘

In [127]:
dois_pmids_isbns_list.group_by(pl.col('id').str.slice(0, 4)).agg(pl.count('id').alias('count')).sort('count', descending=True)

shape: (3, 2)
┌──────┬────────┐
│ id   ┆ count  │
│ ---  ┆ ---    │
│ str  ┆ u32    │
╞══════╪════════╡
│ doi: ┆ 184216 │
│ isbn ┆ 92801  │
│ pmid ┆ 59978  │
└──────┴────────┘

#### Examples of invalid PIDs

In [128]:
# find dois that contain uppercase letters
isbns.filter(pl.col('IDE_ISBN').str.contains(r'[A-Z]')).head()

shape: (5, 3)
┌─────────┬──────────────────────────────────────────────┬───────────────────┐
│ ITEM_ID ┆ IDE_ISBN                                     ┆ OWNING_COLLECTION │
│ ---     ┆ ---                                          ┆ ---               │
│ i64     ┆ str                                          ┆ i64               │
╞═════════╪══════════════════════════════════════════════╪═══════════════════╡
│ 158748  ┆ 978-940075634-2; 940075633X; 978-940075633-5 ┆ 58                │
│ 161548  ┆ 883877708X                                   ┆ 57                │
│ 71680   ┆ AQ8879468243                                 ┆ 41                │
│ 109336  ┆ ISBN 97835406                                ┆ 57                │
│ 67552   ┆ 888215856X                                   ┆ 41                │
└─────────┴──────────────────────────────────────────────┴───────────────────┘

In [129]:
filtered_isbns.filter(pl.col('id').str.contains(r'888809556x')).head()

shape: (2, 3)
┌─────────┬───────────────────┬─────────────────┐
│ iris_id ┆ OWNING_COLLECTION ┆ id              │
│ ---     ┆ ---               ┆ ---             │
│ i64     ┆ i64               ┆ str             │
╞═════════╪═══════════════════╪═════════════════╡
│ 55139   ┆ 49                ┆ isbn:888809556x │
│ 79343   ┆ 49                ┆ isbn:888809556x │
└─────────┴───────────────────┴─────────────────┘

In [130]:
# dois that got filtered out because invalid
doi_anti = dois.join(filtered_dois, left_on='ITEM_ID', right_on='iris_id', how='anti')
doi_anti

shape: (238, 3)
┌─────────┬─────────────────────────┬───────────────────┐
│ ITEM_ID ┆ IDE_DOI                 ┆ OWNING_COLLECTION │
│ ---     ┆ ---                     ┆ ---               │
│ i64     ┆ str                     ┆ i64               │
╞═════════╪═════════════════════════╪═══════════════════╡
│ 8576    ┆ WOS:000340333900012     ┆ 35                │
│ 192899  ┆ 10.193/infdis/jiu617    ┆ 35                │
│ 174463  ┆ 10.746/-fei-XI-02-13_11 ┆ 35                │
│ 176326  ┆ 10.978.886760/1448      ┆ 41                │
│ 178153  ┆ 10.978.886633/1223      ┆ 50                │
│ …       ┆ …                       ┆ …                 │
│ 8575    ┆ WOS:000335369200043     ┆ 35                │
│ 8579    ┆ 000299749300016         ┆ 35                │
│ 10144   ┆ 10.978.88490/03376      ┆ 41                │
│ 10211   ┆ p.2013.12.005           ┆ 35                │
│ 277688  ┆ 10.1016                 ┆ 35                │
└─────────┴─────────────────────────┴───────────────────┘

In [131]:
pmid_anti = pmids.join(filtered_pmids, left_on='ITEM_ID', right_on='iris_id', how='anti')
pmid_anti

shape: (6, 3)
┌─────────┬─────────────┬───────────────────┐
│ ITEM_ID ┆ IDE_PMID    ┆ OWNING_COLLECTION │
│ ---     ┆ ---         ┆ ---               │
│ i64     ┆ str         ┆ i64               │
╞═════════╪═════════════╪═══════════════════╡
│ 554064  ┆ PMC7261988  ┆ 35                │
│ 516464  ┆ PMC7372170  ┆ 35                │
│ 369655  ┆ PMC6186108  ┆ 35                │
│ 153706  ┆ PMC 4874964 ┆ 35                │
│ 380644  ┆ PMC2206475  ┆ 38                │
│ 926697  ┆ 4           ┆ 35                │
└─────────┴─────────────┴───────────────────┘

In [132]:
isbn_anti = isbns.join(filtered_isbns, left_on='ITEM_ID', right_on='iris_id', how='anti')
isbn_anti

shape: (974, 3)
┌─────────┬──────────────────────────────┬───────────────────┐
│ ITEM_ID ┆ IDE_ISBN                     ┆ OWNING_COLLECTION │
│ ---     ┆ ---                          ┆ ---               │
│ i64     ┆ str                          ┆ i64               │
╞═════════╪══════════════════════════════╪═══════════════════╡
│ 82956   ┆ 88.387.3686.3; 88.387.3687.1 ┆ 57                │
│ 196154  ┆ 887946901                    ┆ 50                │
│ 109336  ┆ ISBN 97835406                ┆ 57                │
│ 4823    ┆ 00170089                     ┆ 45                │
│ 4922    ┆ 21189366                     ┆ 41                │
│ …       ┆ …                            ┆ …                 │
│ 302039  ┆ 1414-3283                    ┆ 57                │
│ 79005   ┆ 078039360                    ┆ 57                │
│ 939298  ┆ 979125511                    ┆ 41                │
│ 80398   ┆ 906605699                    ┆ 57                │
│ 137720  ┆ 21561028                     ┆ 57                │
└─────────┴──────────────────────────────┴───────────────────┘

---

## Deduplication

We now have a list of PIDs. However, we have lots of duplicates in the list, both from the iris dataset (e.g. an iris BR has multiple PIDs) and from the external ids (multiple iris BRs that share the same PID).

Let's deal with the former case first:

### 1. Deduplication of iris BRs

Our aim is to keep only a single PID for each iris BR. We will keep the DOI if it exists, otherwise the PMID, and finally the ISBN.

In [134]:
dois_pmids_isbns_list.unique('iris_id')

shape: (262_502, 3)
┌─────────┬───────────┬────────────────────────────────────────┐
│ iris_id ┆ iris_type ┆ id                                     │
│ ---     ┆ ---       ┆ ---                                    │
│ i64     ┆ i64       ┆ str                                    │
╞═════════╪═══════════╪════════════════════════════════════════╡
│ 156564  ┆ 41        ┆ isbn:9788890508219                     │
│ 176976  ┆ 35        ┆ doi:10.1016/j.eururo.2010.10.017       │
│ 680986  ┆ 35        ┆ doi:10.1093/ejcts/ezac408              │
│ 839699  ┆ 35        ┆ doi:10.1707/4317.43030                 │
│ 190466  ┆ 41        ┆ isbn:9788856848915                     │
│ …       ┆ …         ┆ …                                      │
│ 128136  ┆ 35        ┆ doi:10.1016/j.diagmicrobio.2008.09.012 │
│ 604085  ┆ 35        ┆ doi:10.3390/jcs5080214                 │
│ 800631  ┆ 35        ┆ doi:10.1484/j.gif.5.135063             │
│ 69600   ┆ 49        ┆ isbn:8814120323                        │
│ 63675   ┆ 57        ┆ isbn:9781606060131                     │
└─────────┴───────────┴────────────────────────────────────────┘

In [57]:
# number of BRs with multiple types of PIDs in the list
dois_pmids_isbns_list.filter(pl.col('iris_id').is_duplicated()).select(pl.len())

shape: (1, 1)
┌────────┐
│ len    │
│ ---    │
│ u32    │
╞════════╡
│ 148808 │
└────────┘

In [58]:
# example:

# take a look at the BR from IRIS with ID 360
dois_pmids_isbns_list.filter(pl.col('iris_id').is_duplicated()).filter(pl.col('iris_id') == 360).sort('iris_id')

shape: (2, 3)
┌─────────┬───────────┬──────────────────────────────┐
│ iris_id ┆ iris_type ┆ id                           │
│ ---     ┆ ---       ┆ ---                          │
│ i64     ┆ i64       ┆ str                          │
╞═════════╪═══════════╪══════════════════════════════╡
│ 360     ┆ 41        ┆ doi:10.1007/0-387-30394-4_33 │
│ 360     ┆ 41        ┆ isbn:0387298118              │
└─────────┴───────────┴──────────────────────────────┘

In [59]:
# both the DOI and ISBN have been extracted from the BR, so it appears twice in the list of PIDs
df_filtered.filter(pl.col('ITEM_ID') == 360)

shape: (1, 5)
┌─────────┬──────────────────────────┬───────────────┬──────────┬───────────────────┐
│ ITEM_ID ┆ IDE_DOI                  ┆ IDE_ISBN      ┆ IDE_PMID ┆ OWNING_COLLECTION │
│ ---     ┆ ---                      ┆ ---           ┆ ---      ┆ ---               │
│ i64     ┆ str                      ┆ str           ┆ str      ┆ i64               │
╞═════════╪══════════════════════════╪═══════════════╪══════════╪═══════════════════╡
│ 360     ┆ 10.1007/0-387-30394-4_33 ┆ 0-387-29811-8 ┆ null     ┆ 41                │
└─────────┴──────────────────────────┴───────────────┴──────────┴───────────────────┘

In [60]:
dpi_dupes_iris = dois_pmids_isbns_list.filter(pl.col("iris_id").is_duplicated()).sort("iris_id").with_columns(pl.col('iris_type'))#.replace_strict(type_dict))
dpi_dupes_iris_grouped = (dpi_dupes_iris.group_by('iris_id').len().sort('len'))
print('We found', dpi_dupes_iris_grouped.select(pl.len()).item(), 'iris entries that are tied to more than one external identifier')
dpi_dupes_iris_grouped.select(pl.col('len').value_counts()).unnest('len').rename({'len': '# of dupes', 'count': '# of ids'})

We found 74315 iris entries that are tied to more than one external identifier

shape: (2, 2)
┌────────────┬──────────┐
│ # of dupes ┆ # of ids │
│ ---        ┆ ---      │
│ u32        ┆ u32      │
╞════════════╪══════════╡
│ 2          ┆ 74137    │
│ 3          ┆ 178      │
└────────────┴──────────┘

The elements that share the same iris ID all have the same type, so there's no need to create heuristics to decide which one to keep:

In [61]:
same_type = dpi_dupes_iris.group_by("iris_id").agg([
    pl.col("iris_type").n_unique().alias("unique_count")
])
different_types = same_type.filter(pl.col("unique_count") != 1)
different_types

shape: (0, 2)
┌─────────┬──────────────┐
│ iris_id ┆ unique_count │
│ ---     ┆ ---          │
│ i64     ┆ u32          │
╞═════════╪══════════════╡
└─────────┴──────────────┘

To resolve this issue, we keep only the first occurrence of each external id in the list. Given how the list has been constructed, this creates a hierarchical order of preference for the external ids: DOI > PMID > ISBN.

In [62]:
dois_pmids_isbns_list

shape: (336_995, 3)
┌─────────┬───────────┬──────────────────────────────────────┐
│ iris_id ┆ iris_type ┆ id                                   │
│ ---     ┆ ---       ┆ ---                                  │
│ i64     ┆ i64       ┆ str                                  │
╞═════════╪═══════════╪══════════════════════════════════════╡
│ 73478   ┆ 35        ┆ doi:10.2110/palo.2005.p05-020r       │
│ 157248  ┆ 35        ┆ doi:10.1007/jhep07(2012)133          │
│ 155300  ┆ 40        ┆ doi:10.1016/s0021-9290(12)70228-2    │
│ 156226  ┆ 35        ┆ doi:10.1016/j.compstruct.2011.10.026 │
│ 158748  ┆ 58        ┆ doi:10.1007/978-94-007-5634-2_191    │
│ …       ┆ …         ┆ …                                    │
│ 665009  ┆ 57        ┆ isbn:9781450356619                   │
│ 666997  ┆ 58        ┆ isbn:9789727897827                   │
│ 673768  ┆ 57        ┆ isbn:9781665481434                   │
│ 673911  ┆ 41        ┆ isbn:9783805595117                   │
│ 674961  ┆ 50        ┆ isbn:9788855185943                   │
└─────────┴───────────┴──────────────────────────────────────┘

In [63]:
print('num. of ids:', dois_pmids_isbns_list.__len__())
dois_pmids_isbns_filtered = dois_pmids_isbns_list.unique('iris_id', keep='first', maintain_order=True)
print('num. of ids after unique id filtering:', dois_pmids_isbns_filtered.__len__())

num. of ids: 336995
num. of ids after unique id filtering: 262502

In [64]:
dois_pmids_isbns_filtered.group_by(pl.col('id').str.slice(0, 4)).agg(
    pl.len()
).sort('len', descending=True)

shape: (3, 2)
┌──────┬────────┐
│ id   ┆ len    │
│ ---  ┆ ---    │
│ str  ┆ u32    │
╞══════╪════════╡
│ doi: ┆ 184216 │
│ isbn ┆ 76047  │
│ pmid ┆ 2239   │
└──────┴────────┘

### 2. filter out multiple iris entries with the same external id

Let's now deal with the duplicates from the external ids:

In [65]:
#examples:

pids_dupes_df = dois_pmids_isbns_filtered.filter(pl.col("id").is_duplicated()).sort("id").with_columns(pl.col('iris_type'))#.replace(type_dict))
print(pids_dupes_df.n_unique('id'), 'unique PIDs')
pids_dupes_df

# as you can see, the same PIDs are associated to different IRIS BRs

28803 unique PIDs

shape: (86_306, 3)
┌─────────┬───────────┬────────────────────────────────┐
│ iris_id ┆ iris_type ┆ id                             │
│ ---     ┆ ---       ┆ ---                            │
│ i64     ┆ i64       ┆ str                            │
╞═════════╪═══════════╪════════════════════════════════╡
│ 779900  ┆ 35        ┆ doi:10.1001/archderm.130.4.522 │
│ 780022  ┆ 35        ┆ doi:10.1001/archderm.130.4.522 │
│ 853731  ┆ 35        ┆ doi:10.1001/archderm.130.4.522 │
│ 779923  ┆ 35        ┆ doi:10.1001/archderm.132.2.231 │
│ 780060  ┆ 35        ┆ doi:10.1001/archderm.132.2.231 │
│ …       ┆ …         ┆ …                              │
│ 735599  ┆ 35        ┆ pmid:7692192                   │
│ 734698  ┆ 35        ┆ pmid:7692192                   │
│ 733789  ┆ 35        ┆ pmid:7692192                   │
│ 774883  ┆ 35        ┆ pmid:9276009                   │
│ 650493  ┆ 35        ┆ pmid:9276009                   │
└─────────┴───────────┴────────────────────────────────┘

In [66]:
search_dupes = pids_dupes_df.filter(pl.col('id').str.starts_with('isbn:')).sort('iris_id').join(metadata_df, left_on='iris_id', right_on='ITEM_ID', how='left').sort('id')
search_dupes

shape: (47_239, 14)
┌─────────┬───────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ iris_id ┆ iris_type ┆ id         ┆ DATE_ISSU ┆ … ┆ DES_NUMBE ┆ PUB_NAME  ┆ PUB_PLACE ┆ PUB_COUNT │
│ ---     ┆ ---       ┆ ---        ┆ ED_YEAR   ┆   ┆ ROFAUTHOR ┆ ---       ┆ ---       ┆ RY        │
│ i64     ┆ i64       ┆ str        ┆ ---       ┆   ┆ S         ┆ str       ┆ str       ┆ ---       │
│         ┆           ┆            ┆ i64       ┆   ┆ ---       ┆           ┆           ┆ str       │
│         ┆           ┆            ┆           ┆   ┆ i64       ┆           ┆           ┆           │
╞═════════╪═══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 406550  ┆ 57        ┆ isbn:00000 ┆ 2010      ┆ … ┆ 1         ┆ -         ┆ ITA       ┆ ITA       │
│         ┆           ┆ 00000      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 406554  ┆ 57        ┆ isbn:00000 ┆ 2011      ┆ … ┆ 1         ┆ -         ┆ ITA       ┆ ITA       │
│         ┆           ┆ 00000      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 406560  ┆ 57        ┆ isbn:00000 ┆ 2011      ┆ … ┆ 1         ┆ -         ┆ ITA       ┆ ITA       │
│         ┆           ┆ 00000      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 406564  ┆ 57        ┆ isbn:00000 ┆ 2011      ┆ … ┆ 1         ┆ -         ┆ ITA       ┆ ITA       │
│         ┆           ┆ 00000      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 406569  ┆ 57        ┆ isbn:00000 ┆ 2012      ┆ … ┆ 1         ┆ -         ┆ ITA       ┆ ITA       │
│         ┆           ┆ 00000      ┆           ┆   ┆           ┆           ┆           ┆           │
│ …       ┆ …         ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 123085  ┆ 58        ┆ isbn:isbn9 ┆ 2009      ┆ … ┆ 6         ┆ s.n       ┆ s.l       ┆ null      │
│         ┆           ┆ 788890062  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 105822  ┆ 50        ┆ isbn:isbn9 ┆ 2008      ┆ … ┆ 1         ┆ Cineteca  ┆ BOLOGNA   ┆ ITA       │
│         ┆           ┆ 788895862  ┆           ┆   ┆           ┆ di        ┆           ┆           │
│         ┆           ┆            ┆           ┆   ┆           ┆ Bologna   ┆           ┆           │
│ 110789  ┆ 44        ┆ isbn:isbn9 ┆ 2008      ┆ … ┆ 1         ┆ Cineteca  ┆ BOLOGNA   ┆ ITA       │
│         ┆           ┆ 788895862  ┆           ┆   ┆           ┆ di        ┆           ┆           │
│         ┆           ┆            ┆           ┆   ┆           ┆ Bologna   ┆           ┆           │
│ 92987   ┆ 58        ┆ isbn:isbn9 ┆ 2007      ┆ … ┆ 4         ┆ Fintrade  ┆ RIJEKA    ┆ HRV       │
│         ┆           ┆ 789536104  ┆           ┆   ┆           ┆ & Tours   ┆           ┆           │
│         ┆           ┆            ┆           ┆   ┆           ┆ d.o.o.    ┆           ┆           │
│ 92988   ┆ 58        ┆ isbn:isbn9 ┆ 2007      ┆ … ┆ 3         ┆ FINTRADE  ┆ RIJEKA    ┆ HRV       │
│         ┆           ┆ 789536104  ┆           ┆   ┆           ┆ & TOURS   ┆           ┆           │
│         ┆           ┆            ┆           ┆   ┆           ┆ D.O.O.    ┆           ┆           │
└─────────┴───────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [67]:
pids_dupes_df_grouped = (pids_dupes_df.group_by('id').len().sort('len'))
print('We found', pids_dupes_df.select(pl.col('iris_id').unique().len()).item(), 'external ids that are tied to more than one iris entry')
print()
print('The external identifiers appear with the following distribution:')
pids_dupes_df_grouped.select(pl.col('len').value_counts()).unnest('len').rename({'len': '# of dupes', 'count': '# of ext. ids'})

We found 86306 external ids that are tied to more than one iris entry

The external identifiers appear with the following distribution:

shape: (54, 2)
┌────────────┬───────────────┐
│ # of dupes ┆ # of ext. ids │
│ ---        ┆ ---           │
│ u32        ┆ u32           │
╞════════════╪═══════════════╡
│ 2          ┆ 18805         │
│ 3          ┆ 4418          │
│ 4          ┆ 1983          │
│ 5          ┆ 1555          │
│ 6          ┆ 619           │
│ …          ┆ …             │
│ 71         ┆ 1             │
│ 75         ┆ 1             │
│ 79         ┆ 1             │
│ 152        ┆ 1             │
│ 285        ┆ 1             │
└────────────┴───────────────┘

As you can see from the table above, the majority of the external id duplicates are pairs, but we have cases in which the same external id is shared by up to 129 iris entries!! 

The vast majority of the duplicates seem to be coming from the ISBNs:

In [68]:
pids_dupes_df_grouped.with_columns(pl.col('id').str.extract(r'^(doi|pmid|isbn)').alias('id_type')).select(pl.col('id_type').value_counts()).unnest('id_type').sort('id_type', descending=False).rename({'id_type': 'id type', 'count': '# of ext. ids'})
#dpi_dupes_id_grouped

shape: (3, 2)
┌─────────┬───────────────┐
│ id type ┆ # of ext. ids │
│ ---     ┆ ---           │
│ str     ┆ u32           │
╞═════════╪═══════════════╡
│ doi     ┆ 16075         │
│ isbn    ┆ 12617         │
│ pmid    ┆ 111           │
└─────────┴───────────────┘

In [69]:
pids_dupes_df.with_columns(pl.col('id').str.extract(r'^(doi|pmid|isbn)').alias('id_type')).select(pl.col('id_type').value_counts()).unnest('id_type').rename({'id_type': 'id type', 'count': '# of duplicate ext. ids'})

shape: (3, 2)
┌─────────┬─────────────────────────┐
│ id type ┆ # of duplicate ext. ids │
│ ---     ┆ ---                     │
│ str     ┆ u32                     │
╞═════════╪═════════════════════════╡
│ pmid    ┆ 231                     │
│ doi     ┆ 38836                   │
│ isbn    ┆ 47239                   │
└─────────┴─────────────────────────┘

We deal with deduplicating the three different types of id in three different ways:

##### DOI deduplication

In [70]:
doi_dupes_df = pids_dupes_df.filter(pl.col('id').str.starts_with('doi:'))
print(doi_dupes_df.__len__())
doi_dupes_df
#doi_metadata_search = df.join(doi_dupes_df, left_on='ITEM_ID', right_on='iris_id').join(df_iris_description, on='ITEM_ID', how='inner').join(df_iris_relation, on='ITEM_ID', how='inner').join(df_iris_publisher, on='ITEM_ID', how='inner')

38836

shape: (38_836, 3)
┌─────────┬───────────┬────────────────────────────────┐
│ iris_id ┆ iris_type ┆ id                             │
│ ---     ┆ ---       ┆ ---                            │
│ i64     ┆ i64       ┆ str                            │
╞═════════╪═══════════╪════════════════════════════════╡
│ 779900  ┆ 35        ┆ doi:10.1001/archderm.130.4.522 │
│ 780022  ┆ 35        ┆ doi:10.1001/archderm.130.4.522 │
│ 853731  ┆ 35        ┆ doi:10.1001/archderm.130.4.522 │
│ 779923  ┆ 35        ┆ doi:10.1001/archderm.132.2.231 │
│ 780060  ┆ 35        ┆ doi:10.1001/archderm.132.2.231 │
│ …       ┆ …         ┆ …                              │
│ 809529  ┆ 35        ┆ doi:10.7759/cureus.34804       │
│ 6884    ┆ 57        ┆ doi:10.7873/date.2014.155      │
│ 7042    ┆ 57        ┆ doi:10.7873/date.2014.155      │
│ 542790  ┆ 35        ┆ doi:10.9758/cpn.2020.18.4.484  │
│ 621324  ┆ 35        ┆ doi:10.9758/cpn.2020.18.4.484  │
└─────────┴───────────┴────────────────────────────────┘

For what concernes duplicates with the same type, we keep only the first one encountered.

In [71]:
keep_doi = doi_dupes_df.unique(['iris_type', 'id'], keep='first', maintain_order=True)
print(keep_doi.filter(pl.col('id').is_duplicated()).__len__(), 'duplicates remanining;', keep_doi.filter(pl.col('id').is_duplicated()).n_unique('id'), 'unique ids')

2528 duplicates remanining; 1237 unique ids

This leaves 140 duplicate elements (291 entities) with different types. Among each of these we try to pick what we consider the 'container' element by sorting each group of duplicates based on a priority mapping of the types of the elements as described in the IRIS dataset and finally picking the first one. 

We don't need to specify a priority for each and every type present in the dataset, as per our observations the most common source of problems are the ones tied to a restricted set of types.
These problems are also often not coherent among the dataset, so finding a container for each of them is not really feasible. In the harder cases we just keep the first one encountered.

In [72]:
def doi_heuristic(group):
    priority = {
        35: 1, 50: 2, 41: 3, 57: 4
    }

    sorted_iris_types = group.sort(pl.col("iris_type").replace_strict(priority, default=float('inf')))
    return sorted_iris_types.head(1)

keep_doi = keep_doi.group_by("id").map_groups(doi_heuristic)
print('number of doi duplicates remaining: ', keep_doi.filter(pl.col('id').is_duplicated()).__len__())

number of doi duplicates remaining:  0

In [73]:
doi_dupes_list = doi_dupes_df.select('iris_id')
drop_doi = doi_dupes_list.join(keep_doi, on='iris_id', how='anti')

Finally, we remove the dupicates DOIs from the original list of external ids.

In [74]:
dois_pmids_isbns_filtered = dois_pmids_isbns_filtered.join(drop_doi, on='iris_id', how='anti')
dois_pmids_isbns_filtered.__len__()

239741

#### PMID deduplication

In [75]:
pmid_dupes_df = pids_dupes_df.filter(pl.col('id').str.starts_with('pmid:'))
pmid_dupes_df

shape: (231, 3)
┌─────────┬───────────┬───────────────┐
│ iris_id ┆ iris_type ┆ id            │
│ ---     ┆ ---       ┆ ---           │
│ i64     ┆ i64       ┆ str           │
╞═════════╪═══════════╪═══════════════╡
│ 811923  ┆ 35        ┆ pmid:10       │
│ 679280  ┆ 35        ┆ pmid:10       │
│ 923510  ┆ 35        ┆ pmid:10       │
│ 936383  ┆ 35        ┆ pmid:10       │
│ 728542  ┆ 35        ┆ pmid:14524611 │
│ …       ┆ …         ┆ …             │
│ 735599  ┆ 35        ┆ pmid:7692192  │
│ 734698  ┆ 35        ┆ pmid:7692192  │
│ 733789  ┆ 35        ┆ pmid:7692192  │
│ 774883  ┆ 35        ┆ pmid:9276009  │
│ 650493  ┆ 35        ┆ pmid:9276009  │
└─────────┴───────────┴───────────────┘

In [76]:
pmid_dupes_df.group_by('iris_type').agg(pl.len())

shape: (4, 2)
┌───────────┬─────┐
│ iris_type ┆ len │
│ ---       ┆ --- │
│ i64       ┆ u32 │
╞═══════════╪═════╡
│ 35        ┆ 218 │
│ 38        ┆ 4   │
│ 40        ┆ 7   │
│ 57        ┆ 2   │
└───────────┴─────┘

In [77]:
pmid_dupes_df.group_by(
    'id').agg(
        pl.len(),
        pl.col('iris_type').unique()
        ).sort('len', descending=True).filter(pl.col('iris_type').list.len() > 1)

# articles (35) are in all ambiguous duplicates

shape: (6, 3)
┌───────────────┬─────┬───────────┐
│ id            ┆ len ┆ iris_type │
│ ---           ┆ --- ┆ ---       │
│ str           ┆ u32 ┆ list[i64] │
╞═══════════════╪═════╪═══════════╡
│ pmid:15614151 ┆ 2   ┆ [35, 38]  │
│ pmid:16437895 ┆ 2   ┆ [35, 40]  │
│ pmid:18560115 ┆ 2   ┆ [35, 57]  │
│ pmid:21273609 ┆ 2   ┆ [35, 40]  │
│ pmid:21341571 ┆ 2   ┆ [35, 57]  │
│ pmid:23749883 ┆ 2   ┆ [35, 38]  │
└───────────────┴─────┴───────────┘

In [78]:
print(pmid_dupes_df.filter(pl.col('id').is_duplicated()).__len__(), 'duplicates remanining;', pmid_dupes_df.filter(pl.col('id').is_duplicated()).n_unique('id'), 'unique ids')
keep_pmid = pmid_dupes_df.unique(['iris_type', 'id'], keep='first', maintain_order=True)
print('----')
print(keep_pmid.filter(pl.col('id').is_duplicated()).__len__(), 'duplicates remanining;', keep_pmid.filter(pl.col('id').is_duplicated()).n_unique('id'), 'unique ids')

231 duplicates remanining; 111 unique ids
----
12 duplicates remanining; 6 unique ids

In [79]:
def pmid_heuristic(group):
    priority = {
        35: 1
    }

    sorted_iris_types = group.sort(pl.col("iris_type").replace_strict(priority, default=float('inf')))
    return sorted_iris_types.head(1)

keep_pmid = keep_pmid.group_by("id").map_groups(pmid_heuristic)
print('number of doi duplicates remaining: ', keep_pmid.filter(pl.col('id').is_duplicated()).__len__())

number of doi duplicates remaining:  0

In [80]:
pmid_dupes_list = pmid_dupes_df.select('iris_id')
drop_pmid = pmid_dupes_list.join(keep_pmid, on='iris_id', how='anti')

In [81]:
dois_pmids_isbns_filtered = dois_pmids_isbns_filtered.join(drop_pmid, on='iris_id', how='anti')
dois_pmids_isbns_filtered.__len__()

239621

#### Deduplicate ISBN

In [82]:
isbn_dupes_df = pids_dupes_df.filter(pl.col('id').str.starts_with('isbn:'))
print(isbn_dupes_df.__len__(), '| unique isbns: ', isbn_dupes_df.unique('id').__len__())

#isbn_search = df.join(doi_dupes_df, left_on='ITEM_ID', right_on='iris_id').join(df_iris_description, on='ITEM_ID', how='inner').join(df_iris_relation, on='ITEM_ID', how='inner').join(df_iris_publisher, on='ITEM_ID', how='inner')

#doi_search.sort('id').head(6)

47239 | unique isbns:  12617

We keep only the first occurrence of the entries with the same external id and type:

In [83]:
keep_isbn = isbn_dupes_df.unique(['iris_type', 'id'], keep='first', maintain_order=True)
print('the number of elements came down to', keep_isbn.__len__(), 'but there are still', keep_isbn.filter(pl.col('id').is_duplicated()).__len__(), 'duplicates')

the number of elements came down to 21052 but there are still 15032 duplicates

And then we pick the entries that have the same external id but different types based on a priority list. (note that, if not specified in the priority list, the heuristic will only keep the top-most entry like it has found it in the df.)

In [84]:
isbn_dupes_df.group_by(
    'id').agg(
        pl.len(),
        pl.col('iris_type').unique()
).sort('len', descending=True).filter(pl.col('iris_type').list.len() > 1)

shape: (6_597, 3)
┌─────────────────────┬─────┬──────────────┐
│ id                  ┆ len ┆ iris_type    │
│ ---                 ┆ --- ┆ ---          │
│ str                 ┆ u32 ┆ list[i64]    │
╞═════════════════════╪═════╪══════════════╡
│ isbn:9788812000326  ┆ 285 ┆ [41, 45, 50] │
│ isbn:9788870757279  ┆ 152 ┆ [41, 45]     │
│ isbn:9788861328112  ┆ 79  ┆ [41, 46]     │
│ isbn:9788861323377  ┆ 75  ┆ [41, 45]     │
│ isbn:9788861321304  ┆ 71  ┆ [41, 45, 50] │
│ …                   ┆ …   ┆ …            │
│ isbn:9963607667     ┆ 2   ┆ [57, 58]     │
│ isbn:9974324246     ┆ 2   ┆ [41, 50]     │
│ isbn:9978224793     ┆ 2   ┆ [41, 50]     │
│ isbn:9994392301     ┆ 2   ┆ [41, 46]     │
│ isbn:isbn9788895862 ┆ 2   ┆ [44, 50]     │
└─────────────────────┴─────┴──────────────┘

In [85]:
def isbn_heuristic(group):
    priority = {
        49: 1, 35: 2 #aggiungere 50-curatela?
    }

    sorted_iris_types = group.sort(pl.col("iris_type").replace_strict(priority, default=float('inf')))
    return sorted_iris_types.head(1)

keep_isbn = keep_isbn.group_by("id").map_groups(isbn_heuristic)
keep_isbn.__len__(), keep_isbn.filter(pl.col('id').is_duplicated()).__len__()

(12617, 0)

In [86]:
isbn_dupes_list = isbn_dupes_df.select('iris_id')
drop_isbn = isbn_dupes_list.join(keep_isbn, on='iris_id', how='anti')

In [87]:
dois_pmids_isbns_filtered = dois_pmids_isbns_filtered.join(drop_isbn, on='iris_id', how='anti')
dois_pmids_isbns_filtered.__len__()

204999

In [88]:
print('number of duplicates ext. ids: ', dois_pmids_isbns_filtered.filter(pl.col('id').is_duplicated()).__len__())

number of duplicates ext. ids:  0

## Create IIM

Now that we have a clean, deduplicated list of external ids, we can filter the Meta dump to keep only the entries that have at least one of these external ids. We then save this filtered dataframe to a parquet file.

In [89]:
meta_path = Path('../data/csv_openalex.zip')

In [90]:
dois_pmids_isbns_filtered

shape: (204_999, 3)
┌─────────┬───────────┬──────────────────────────────────────┐
│ iris_id ┆ iris_type ┆ id                                   │
│ ---     ┆ ---       ┆ ---                                  │
│ i64     ┆ i64       ┆ str                                  │
╞═════════╪═══════════╪══════════════════════════════════════╡
│ 73478   ┆ 35        ┆ doi:10.2110/palo.2005.p05-020r       │
│ 157248  ┆ 35        ┆ doi:10.1007/jhep07(2012)133          │
│ 155300  ┆ 40        ┆ doi:10.1016/s0021-9290(12)70228-2    │
│ 156226  ┆ 35        ┆ doi:10.1016/j.compstruct.2011.10.026 │
│ 158748  ┆ 58        ┆ doi:10.1007/978-94-007-5634-2_191    │
│ …       ┆ …         ┆ …                                    │
│ 943298  ┆ 41        ┆ isbn:9791259561527                   │
│ 943324  ┆ 41        ┆ isbn:9788891935434                   │
│ 940793  ┆ 49        ┆ isbn:9788894331165                   │
│ 941422  ┆ 41        ┆ isbn:9788868973575                   │
│ 941592  ┆ 41        ┆ isbn:9788893854771                   │
└─────────┴───────────┴──────────────────────────────────────┘

In [ ]:
def process_meta_zip(zip_path):
    zip_file = ZipFile(zip_path)
    files_list = [zipfile for zipfile in zip_file.namelist() if zipfile.endswith('.csv')]
    output_iim = Path("../data/iris_in_meta")

    #dois_pmids_isbns_lf = dois_pmids_isbns_list.lazy()
    dois_pmids_isbns_lf = dois_pmids_isbns_filtered.lazy()

    for csv_file in tqdm(files_list, desc="Processing Meta CSV files"):
        with zip_file.open(csv_file, 'r') as file:
            # kudos to https://vdavez.com/2024/01/how-to-use-scan_csv-with-a-file-like-object-in-polars/
            with tempfile.NamedTemporaryFile() as tf:
                tf.write(file.read())
                tf.seek(0)
                os.makedirs(output_iim, exist_ok=True)
                df = (
                    pl.scan_csv(tf.name)
                    .select(['id', 'title', 'type'])
                    .with_columns(
                        (pl.col('id').str.extract(r"(omid:[^\s]+)")).alias('omid'),
                        (pl.col('id').str.extract(r"((?:doi):[^\s\"]+)")).alias('doi'),
                        (pl.col('id').str.extract(r"((?:pmid):[^\s\"]+)")).alias('pmid'),
                        (pl.col('id').str.extract(r"((?:isbn):[^\s\"]+)")).alias('isbn'),
                    )
                    .with_columns(
                        pl.coalesce([pl.col('doi'), pl.col('pmid'), pl.col('isbn')]).alias('id')
                    )
                    .drop(['doi', 'pmid', 'isbn'])
                    .drop_nulls('id')
                    .join(dois_pmids_isbns_lf, on='id', how='inner')
                    .collect(streaming=True)
                )

            if not df.is_empty():
                df.write_parquet(os.path.join(output_iim, os.path.basename(csv_file).replace('.csv', '.parquet')))



process_meta_zip(meta_path)

Processing Meta CSV files:   0%|          | 0/28248 [00:00<?, ?it/s]

---

Analysing the Iris in Meta dataset, we see that another source of problems come from the Meta dataset itself, in which some of the entries have different OMID ids but share the same external id. Talking about this with pr. Peroni, we learned that this is in fact an issue in the Meta dump (that will be resolved in the near future).

In [101]:
lf_iim = pl.scan_parquet('../data/iris_in_meta/temp_chunks/*.parquet')

lf_iim.select(pl.len()).collect()

shape: (1, 1)
┌────────┐
│ len    │
│ ---    │
│ u32    │
╞════════╡
│ 145724 │
└────────┘

In [102]:
lf_iim.with_columns(pl.col('pub_date').str.extract(r'\d{4}', 0).alias('year').str.to_date(format="%Y")).filter(pl.col('year') < 1953).collect()

shape: (4, 9)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ id         ┆ title     ┆ type      ┆ pub_date  ┆ … ┆ iris_id ┆ iris_type ┆ iris_pub_ ┆ year      │
│ ---        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---     ┆ ---       ┆ year      ┆ ---       │
│ str        ┆ str       ┆ str       ┆ str       ┆   ┆ i64     ┆ i64       ┆ ---       ┆ date      │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ i32       ┆           │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ doi:10.101 ┆ Effect Of ┆ journal   ┆ 1975-10   ┆ … ┆ 926697  ┆ 35        ┆ 1975      ┆ 1975-01-0 │
│ 6/0006-291 ┆ Chloroqui ┆ article   ┆           ┆   ┆         ┆           ┆           ┆ 1         │
│ x(75)90506 ┆ ne On     ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ -9         ┆ Cultured  ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ Fibroblas ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ ts:       ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ Release   ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ Of        ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ Lysosomal ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ Hydrolase ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ s And Inh ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ ibition   ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ Of The…   ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ pmid:10    ┆ Digitoxin ┆ journal   ┆ 1975      ┆ … ┆ 811923  ┆ 35        ┆ 1975      ┆ 1975-01-0 │
│            ┆ Metabolis ┆ article   ┆           ┆   ┆         ┆           ┆           ┆ 1         │
│            ┆ m By Rat  ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ Liver Mic ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ rosomes.  ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ doi:10.101 ┆ The       ┆ book      ┆ 1920-12-3 ┆ … ┆ 260326  ┆ 41        ┆ 2016      ┆ 1920-01-0 │
│ 7/cbo97813 ┆ Autonomy  ┆ chapter   ┆ 1         ┆   ┆         ┆           ┆           ┆ 1         │
│ 16597873.0 ┆ Of Techno ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ 03         ┆ logical   ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ Systems   ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ And Respo ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ nsibiliti ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ es For    ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ Their Use ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ doi:10.101 ┆ Effect Of ┆ journal   ┆ 1975      ┆ … ┆ 926697  ┆ 35        ┆ 1975      ┆ 1975-01-0 │
│ 6/0006-291 ┆ Chloroqui ┆ article   ┆           ┆   ┆         ┆           ┆           ┆ 1         │
│ x(75)90506 ┆ ne On     ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ -9         ┆ Cultured  ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ Fibroblas ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ ts:       ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ Release   ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ Of        ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ Lysosomal ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ Hydrolase ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ s And Inh ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ ibition   ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ Of The…   ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

In [103]:
#example of duplicates
lf_iim.filter(pl.col('id').str.contains('doi')).filter(pl.col('id').is_duplicated()).sort('id').head(6).collect()

shape: (6, 8)
┌─────────────┬─────────────┬─────────┬──────────┬─────────────┬─────────┬───────────┬─────────────┐
│ id          ┆ title       ┆ type    ┆ pub_date ┆ omid        ┆ iris_id ┆ iris_type ┆ iris_pub_ye │
│ ---         ┆ ---         ┆ ---     ┆ ---      ┆ ---         ┆ ---     ┆ ---       ┆ ar          │
│ str         ┆ str         ┆ str     ┆ str      ┆ str         ┆ i64     ┆ i64       ┆ ---         │
│             ┆             ┆         ┆          ┆             ┆         ┆           ┆ i32         │
╞═════════════╪═════════════╪═════════╪══════════╪═════════════╪═════════╪═══════════╪═════════════╡
│ doi:10.1016 ┆ Evaluation  ┆ journal ┆ 1984-08  ┆ omid:br/063 ┆ 787666  ┆ 35        ┆ 1984        │
│ /0002-8703( ┆ Of The      ┆ article ┆          ┆ 01552302    ┆         ┆           ┆             │
│ 84)90608-2  ┆ Effects Of  ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Catheter    ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Sampling    ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ For The     ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Study Of    ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Platelet    ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Behavior In ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ The         ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Pulmonary   ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ A…          ┆         ┆          ┆             ┆         ┆           ┆             │
│ doi:10.1016 ┆ Evaluation  ┆ journal ┆ 1984     ┆ omid:br/061 ┆ 787666  ┆ 35        ┆ 1984        │
│ /0002-8703( ┆ Of The      ┆ article ┆          ┆ 04035916    ┆         ┆           ┆             │
│ 84)90608-2  ┆ Effects Of  ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Catheter    ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Sampling    ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ For The     ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Study Of    ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Platelet    ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Behavior In ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ The         ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Pulmonary   ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ A…          ┆         ┆          ┆             ┆         ┆           ┆             │
│ doi:10.1016 ┆ Differentia ┆ journal ┆ 1986-08  ┆ omid:br/061 ┆ 787705  ┆ 35        ┆ 1986        │
│ /0002-8703( ┆ l Transmyoc ┆ article ┆          ┆ 401528754   ┆         ┆           ┆             │
│ 86)90259-0  ┆ ardial      ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Platelet    ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Behavior In ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Response To ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Pacing And  ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Ergonovine- ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Induced     ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Myocardi…   ┆         ┆          ┆             ┆         ┆           ┆             │
│ doi:10.1016 ┆ Differentia ┆ journal ┆ 1986     ┆ omid:br/062 ┆ 787705  ┆ 35        ┆ 1986        │
│ /0002-8703( ┆ l Transmyoc ┆ article ┆          ┆ 203596606   ┆         ┆           ┆             │
│ 86)90259-0  ┆ ardial      ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Platelet    ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Behavior In ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Response To ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Pacing And  ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Ergonovine- ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Induced     ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Myocardi…   ┆         ┆          ┆             ┆         ┆           ┆             │
│ doi:10.1016 ┆ Myocardial  ┆ journal ┆ 1987-02  ┆ omid:br/061 ┆ 787638  ┆ 35        ┆ 1987        │
│ /0002-8703( ┆ Ischemia    ┆ article ┆          ┆ 601551538   ┆         ┆           ┆             │
│ 87)90259-6  ┆ During      ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Intravenous ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Prostacycli ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ n Administr ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ ation:      ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Hemodynamic ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Findings    ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ And         ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Precaut…    ┆         ┆          ┆             ┆         ┆           ┆             │
│ doi:10.1016 ┆ Myocardial  ┆ journal ┆ 1987     ┆ omid:br/062 ┆ 787638  ┆ 35        ┆ 1987        │
│ /0002-8703( ┆ Ischemia    ┆ article ┆          ┆ 203595952   ┆         ┆           ┆             │
│ 87)90259-6  ┆ During      ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Intravenous ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Prostacycli ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ n Administr ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ ation:      ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Hemodynamic ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Findings    ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ And         ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Precaut…    ┆         ┆          ┆             ┆         ┆           ┆             │
└─────────────┴─────────────┴─────────┴──────────┴─────────────┴─────────┴───────────┴─────────────┘

In [105]:
print(lf_iim.filter(pl.col('id').is_duplicated()).select(pl.len()).collect().item(), 'items are duplicates')

1121 items are duplicates

In [108]:
lf_iim.head().collect()

shape: (5, 8)
┌────────────┬────────────┬────────────┬────────────┬────────────┬─────────┬───────────┬───────────┐
│ id         ┆ title      ┆ type       ┆ pub_date   ┆ omid       ┆ iris_id ┆ iris_type ┆ iris_pub_ │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---     ┆ ---       ┆ year      │
│ str        ┆ str        ┆ str        ┆ str        ┆ str        ┆ i64     ┆ i64       ┆ ---       │
│            ┆            ┆            ┆            ┆            ┆         ┆           ┆ i32       │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═════════╪═══════════╪═══════════╡
│ doi:10.211 ┆ Reconstruc ┆ book       ┆ 1991       ┆ omid:br/06 ┆ 692197  ┆ 35        ┆ 1991      │
│ 0/pec.91.4 ┆ tion Of    ┆ chapter    ┆            ┆ 2503148795 ┆         ┆           ┆           │
│ 5.0227     ┆ Oligo-Mioc ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ ene Volcan ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ iclastic   ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ Dispersal  ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ Patterns   ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ In North-C ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ entral New ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ Mexico     ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ Using …    ┆            ┆            ┆            ┆         ┆           ┆           │
│ doi:10.402 ┆ Investigat ┆ proceeding ┆ 2010-10-27 ┆ omid:br/06 ┆ 244462  ┆ 41        ┆ 2010      │
│ 8/www.scie ┆ ion Of Flu ┆ s article  ┆            ┆ 2503150465 ┆         ┆           ┆           │
│ ntific.net ┆ ctuating   ┆            ┆            ┆            ┆         ┆           ┆           │
│ /ast.75.14 ┆ Diamagneti ┆            ┆            ┆            ┆         ┆           ┆           │
│ 1          ┆ sm And     ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ Spin       ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ Dynamics   ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ In SmFeAsO ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ <sub>1-x</ ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ sub>F<sub> ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ x</sub>    ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ Su…        ┆            ┆            ┆            ┆         ┆           ┆           │
│ doi:10.101 ┆ A High     ┆ journal    ┆ 2006-01    ┆ omid:br/06 ┆ 85136   ┆ 35        ┆ 2006      │
│ 6/j.nuclph ┆ Spatial    ┆ article    ┆            ┆ 1702810140 ┆         ┆           ┆           │
│ ysbps.2004 ┆ Resolution ┆            ┆            ┆            ┆         ┆           ┆           │
│ .06.012    ┆ CT Scanner ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ For Small  ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ Animal     ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ Imaging    ┆            ┆            ┆            ┆         ┆           ┆           │
│ doi:10.100 ┆ Teleologic ┆ journal    ┆ 2012-02-03 ┆ omid:br/06 ┆ 148686  ┆ 35        ┆ 2013      │
│ 7/s10503-0 ┆ al Justifi ┆ article    ┆            ┆ 1702808974 ┆         ┆           ┆           │
│ 12-9262-y  ┆ cation Of  ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ Argumentat ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ ion        ┆            ┆            ┆            ┆         ┆           ┆           │
│            ┆ Schemes    ┆            ┆            ┆            ┆         ┆           ┆           │
│ doi:10.100 ┆ Reasoning  ┆ journal    ┆ 2005-11    ┆ omid:br/06 ┆ 77053   ┆ 35        ┆ 2005      │
│ 7/s10503-0 ┆ With       ┆ article    ┆            ┆ 1702809192 ┆         ┆           ┆           │
│ 05-0509-8  ┆ Factors    ┆            ┆            ┆            ┆         ┆           ┆           │
└────────────┴────────────┴────────────┴────────────┴────────────┴─────────┴───────────┴───────────┘

In [109]:
lf_iim.filter(pl.col('id').is_duplicated()).filter(pl.col('type') == '').collect()

shape: (0, 8)
┌─────┬───────┬──────┬──────────┬──────┬─────────┬───────────┬───────────────┐
│ id  ┆ title ┆ type ┆ pub_date ┆ omid ┆ iris_id ┆ iris_type ┆ iris_pub_year │
│ --- ┆ ---   ┆ ---  ┆ ---      ┆ ---  ┆ ---     ┆ ---       ┆ ---           │
│ str ┆ str   ┆ str  ┆ str      ┆ str  ┆ i64     ┆ i64       ┆ i32           │
╞═════╪═══════╪══════╪══════════╪══════╪═════════╪═══════════╪═══════════════╡
└─────┴───────┴──────┴──────────┴──────┴─────────┴───────────┴───────────────┘

Out of these duplicates, we see that all but 28 elements have the same type. Let us deal with these cases first:

In [110]:
same_id_multpile_type_count = lf_iim.filter(pl.col('id').is_duplicated()).collect().group_by("iris_id").agg([
    pl.col("type").n_unique().alias("type_unique_count")
]).filter(pl.col("type_unique_count") != 1)
same_id_multpile_type_count.sort('type_unique_count')

shape: (11, 2)
┌─────────┬───────────────────┐
│ iris_id ┆ type_unique_count │
│ ---     ┆ ---               │
│ i64     ┆ u32               │
╞═════════╪═══════════════════╡
│ 660762  ┆ 2                 │
│ 666743  ┆ 2                 │
│ 402578  ┆ 2                 │
│ 336128  ┆ 2                 │
│ 632062  ┆ 2                 │
│ …       ┆ …                 │
│ 848549  ┆ 2                 │
│ 405139  ┆ 2                 │
│ 680985  ┆ 2                 │
│ 287218  ┆ 2                 │
│ 113506  ┆ 2                 │
└─────────┴───────────────────┘

Analyzing these 74 duplicates we see that there are a lot of entries with empty types and titles. Our first shot is to get rid of those entries.

In [112]:
different_omid_different_type = lf_iim.filter(pl.col('iris_id').is_in(same_id_multpile_type_count.get_column('iris_id'))).sort('id').collect()
different_omid_different_type

/tmp/ipykernel_1321658/3243381722.py:1: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  different_omid_different_type = lf_iim.filter(pl.col('iris_id').is_in(same_id_multpile_type_count.get_column('iris_id'))).sort('id').collect()

shape: (35, 8)
┌─────────────┬─────────────┬─────────┬──────────┬─────────────┬─────────┬───────────┬─────────────┐
│ id          ┆ title       ┆ type    ┆ pub_date ┆ omid        ┆ iris_id ┆ iris_type ┆ iris_pub_ye │
│ ---         ┆ ---         ┆ ---     ┆ ---      ┆ ---         ┆ ---     ┆ ---       ┆ ar          │
│ str         ┆ str         ┆ str     ┆ str      ┆ str         ┆ i64     ┆ i64       ┆ ---         │
│             ┆             ┆         ┆          ┆             ┆         ┆           ┆ i32         │
╞═════════════╪═════════════╪═════════╪══════════╪═════════════╪═════════╪═══════════╪═════════════╡
│ doi:10.1016 ┆ Smoking And ┆ journal ┆ 1991-01  ┆ omid:br/066 ┆ 632062  ┆ 35        ┆ 1991        │
│ /0277-5379( ┆ Cancer With ┆ article ┆          ┆ 0737482     ┆         ┆           ┆             │
│ 91)90071-k  ┆ Emphasis On ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Europe      ┆         ┆          ┆             ┆         ┆           ┆             │
│ doi:10.1016 ┆ null        ┆ null    ┆ null     ┆ omid:br/065 ┆ 632062  ┆ 35        ┆ 1991        │
│ /0277-5379( ┆             ┆         ┆          ┆ 10222862    ┆         ┆           ┆             │
│ 91)90071-k  ┆             ┆         ┆          ┆             ┆         ┆           ┆             │
│ doi:10.1016 ┆ Smoking And ┆ journal ┆ 1991     ┆ omid:br/061 ┆ 632062  ┆ 35        ┆ 1991        │
│ /0277-5379( ┆ Cancer With ┆ article ┆          ┆ 503643868   ┆         ┆           ┆             │
│ 91)90071-k  ┆ Emphasis On ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Europe.     ┆         ┆          ┆             ┆         ┆           ┆             │
│ doi:10.1016 ┆ Surgical    ┆ journal ┆ 1998     ┆ omid:br/067 ┆ 680985  ┆ 35        ┆ 1998        │
│ /s0003-4975 ┆ Indications ┆ article ┆          ┆ 04013261    ┆         ┆           ┆             │
│ (97)01302-7 ┆ And Timing  ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Of Repair   ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Of          ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Traumatic   ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Ruptures Of ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ The         ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Thoracic    ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Aorta.      ┆         ┆          ┆             ┆         ┆           ┆             │
│ doi:10.1016 ┆ null        ┆ null    ┆ null     ┆ omid:br/064 ┆ 680985  ┆ 35        ┆ 1998        │
│ /s0003-4975 ┆             ┆         ┆          ┆ 04620367    ┆         ┆           ┆             │
│ (97)01302-7 ┆             ┆         ┆          ┆             ┆         ┆           ┆             │
│ …           ┆ …           ┆ …       ┆ …        ┆ …           ┆ …       ┆ …         ┆ …           │
│ doi:10.1016 ┆ null        ┆ null    ┆ null     ┆ omid:br/061 ┆ 402516  ┆ 35        ┆ 2018        │
│ /s0140-6736 ┆             ┆         ┆          ┆ 203942999   ┆         ┆           ┆             │
│ (18)32281-5 ┆             ┆         ┆          ┆             ┆         ┆           ┆             │
│ doi:10.1016 ┆ Measuring   ┆ journal ┆ 2018     ┆ omid:br/062 ┆ 402516  ┆ 35        ┆ 2018        │
│ /s0140-6736 ┆ Progress    ┆ article ┆          ┆ 403726319   ┆         ┆           ┆             │
│ (18)32281-5 ┆ From 1990   ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ To 2017 And ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Projecting  ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Attainment  ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ To 2030 Of  ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ The Health- ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Related     ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Sustain…    ┆         ┆          ┆             ┆         ┆           ┆             │
│ doi:10.1016 ┆ Active Or   ┆ journal ┆ 1994     ┆ omid:br/062 ┆ 848549  ┆ 35        ┆ 1994        │
│ /s0140-6736 ┆ Recent      ┆ article ┆          ┆ 503706728   ┆         ┆           ┆             │
│ (94)92154-7 ┆ Parvovirus  ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ B19         ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Infection   ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ In Children ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ With        ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Kawasaki    ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Disease.    ┆         ┆          ┆             ┆         ┆           ┆             │
│ doi:10.1016 ┆ Active Or   ┆ journal ┆ 1994-05  ┆ omid:br/063 ┆ 848549  ┆ 35        ┆ 1994        │
│ /s0140-6736 ┆ Recent      ┆ article ┆          ┆ 0825585     ┆         ┆           ┆             │
│ (94)92154-7 ┆ Parvovirus  ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ B19         ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Infection   ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ In Children ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ With        ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Kawasaki    ┆         ┆          ┆             ┆         ┆           ┆             │
│             ┆ Disease     ┆         ┆          ┆             ┆         ┆           ┆             │
│ doi:10.1016 ┆ null        ┆ null    ┆ null     ┆ omid:br/061 ┆ 848549  ┆ 35        ┆ 1994        │
│ /s0140-6736 ┆             ┆         ┆          ┆ 804162803   ┆         ┆           ┆             │
│ (94)92154-7 ┆             ┆         ┆          ┆             ┆         ┆           ┆             │
└─────────────┴─────────────┴─────────┴──────────┴─────────────┴─────────┴───────────┴─────────────┘

In [ ]:
to_drop = different_omid_different_type.filter(pl.col('type') == "")
print('bingo: the number of unique elements remains the same at', different_omid_different_type.join(to_drop, on='omid', how='anti').n_unique('id'), 'so we did not delete any unique value.')

bingo: the number of unique elements remains the same at 28 so we did not delete any unique value.

Analyzing the remaining entries, we see that there remain only 16 duplicates with different types.

In [ ]:
different_omid_different_type2 = different_omid_different_type.join(to_drop, on='omid', how='anti')
same_id_multiple_type_count2 = different_omid_different_type2.filter(pl.col('id').is_duplicated()).group_by("iris_id").agg([
    pl.col("type").n_unique().alias("type_unique_count")
]).filter(pl.col("type_unique_count") != 1)
same_id_multiple_type_count2

shape: (8, 2)
┌─────────┬───────────────────┐
│ iris_id ┆ type_unique_count │
│ ---     ┆ ---               │
│ i64     ┆ u32               │
╞═════════╪═══════════════════╡
│ 74637   ┆ 2                 │
│ 369184  ┆ 2                 │
│ 134111  ┆ 2                 │
│ 92438   ┆ 2                 │
│ 666743  ┆ 2                 │
│ 84288   ┆ 2                 │
│ 700389  ┆ 2                 │
│ 673035  ┆ 2                 │
└─────────┴───────────────────┘

In [ ]:
different_omid_different_type2 = different_omid_different_type2.filter(pl.col('iris_id').is_in(same_id_multiple_type_count2.get_column('iris_id'))).sort('id')

We can see that 16 entries remain still. These have the same iris id, but different omid and most importantly different types. We decide to keep only the elements that align with the type of the iris dataset.

In [ ]:
different_omid_different_type2.select(pl.col('iris_type').value_counts())

shape: (3, 1)
┌───────────┐
│ iris_type │
│ ---       │
│ struct[2] │
╞═══════════╡
│ {35,4}    │
│ {41,10}   │
│ {42,2}    │
└───────────┘

In [ ]:
dict_df = pl.DataFrame({
    "iris_type": [35, 41, 42],
    "type": ['journal article', 'book chapter', 'book chapter']
})

to_drop2 = different_omid_different_type2.join(dict_df, on=["iris_type", "type"], how='anti')
different_omid_different_type3 = different_omid_different_type2.join(to_drop2, on='omid', how='anti').filter(pl.col('id').is_duplicated()).sort('id')
different_omid_different_type3 # no duplicates !!

shape: (0, 6)
┌─────┬───────┬──────┬──────┬─────────┬───────────┐
│ id  ┆ title ┆ type ┆ omid ┆ iris_id ┆ iris_type │
│ --- ┆ ---   ┆ ---  ┆ ---  ┆ ---     ┆ ---       │
│ str ┆ str   ┆ str  ┆ str  ┆ i64     ┆ i64       │
╞═════╪═══════╪══════╪══════╪═════════╪═══════════╡
└─────┴───────┴──────┴──────┴─────────┴───────────┘

In [ ]:
to_drop = pl.concat([to_drop, to_drop2])
to_drop

shape: (35, 6)
┌───────────────────┬───────────────────┬─────────────────┬──────────────────┬─────────┬───────────┐
│ id                ┆ title             ┆ type            ┆ omid             ┆ iris_id ┆ iris_type │
│ ---               ┆ ---               ┆ ---             ┆ ---              ┆ ---     ┆ ---       │
│ str               ┆ str               ┆ str             ┆ str              ┆ i64     ┆ i64       │
╞═══════════════════╪═══════════════════╪═════════════════╪══════════════════╪═════════╪═══════════╡
│ doi:10.1007/jhep0 ┆ Analytic Helicity ┆                 ┆ omid:br/06604294 ┆ 560558  ┆ 35        │
│ 1(2019)186        ┆ Amplitudes For    ┆                 ┆ 851              ┆         ┆           │
│                   ┆ Two-Loop          ┆                 ┆                  ┆         ┆           │
│                   ┆ Five-Gluon        ┆                 ┆                  ┆         ┆           │
│                   ┆ Scattering: The   ┆                 ┆                  ┆         ┆           │
│                   ┆ Single-Minus Case ┆                 ┆                  ┆         ┆           │
│ doi:10.1007/jhep0 ┆ Search For        ┆                 ┆ omid:br/06404321 ┆ 391724  ┆ 35        │
│ 9(2018)007        ┆ Additional        ┆                 ┆ 301              ┆         ┆           │
│                   ┆ Neutral MSSM      ┆                 ┆                  ┆         ┆           │
│                   ┆ Higgs Bosons In   ┆                 ┆                  ┆         ┆           │
│                   ┆ The Τ Τ Final     ┆                 ┆                  ┆         ┆           │
│                   ┆ State In          ┆                 ┆                  ┆         ┆           │
│                   ┆ Proton-Proton     ┆                 ┆                  ┆         ┆           │
│                   ┆ Collisions A…     ┆                 ┆                  ┆         ┆           │
│ doi:10.1007/jhep1 ┆ Planar Master     ┆                 ┆ omid:br/06504258 ┆ 769982  ┆ 35        │
│ 2(2018)019        ┆ Integrals For The ┆                 ┆ 303              ┆         ┆           │
│                   ┆ Two-Loop          ┆                 ┆                  ┆         ┆           │
│                   ┆ Light-Fermion     ┆                 ┆                  ┆         ┆           │
│                   ┆ Electroweak       ┆                 ┆                  ┆         ┆           │
│                   ┆ Corrections To    ┆                 ┆                  ┆         ┆           │
│                   ┆ Higgs Plus Jet    ┆                 ┆                  ┆         ┆           │
│                   ┆ Pro…              ┆                 ┆                  ┆         ┆           │
│ doi:10.1016/0277- ┆                   ┆                 ┆ omid:br/06510222 ┆ 632062  ┆ 35        │
│ 5379(91)90071-k   ┆                   ┆                 ┆ 862              ┆         ┆           │
│ doi:10.1016/s0014 ┆                   ┆                 ┆ omid:br/06470234 ┆ 660762  ┆ 35        │
│ -5793(97)01073-9  ┆                   ┆                 ┆ 045              ┆         ┆           │
│ doi:10.1016/s0140 ┆                   ┆                 ┆ omid:br/06410213 ┆ 113506  ┆ 35        │
│ -6736(06)68338-4  ┆                   ┆                 ┆ 596              ┆         ┆           │
│ doi:10.1016/s0140 ┆                   ┆                 ┆ omid:br/06310328 ┆ 287218  ┆ 35        │
│ -6736(16)31467-2  ┆                   ┆                 ┆ 682              ┆         ┆           │
│ doi:10.1016/s0140 ┆                   ┆                 ┆ omid:br/06510324 ┆ 336128  ┆ 35        │
│ -6736(17)32152-9  ┆                   ┆                 ┆ 330              ┆         ┆           │
│ doi:10.1016/s0140 ┆                   ┆                 ┆ omid:br/06120394 ┆ 405139  ┆ 35        │
│ -6736(18)32278-5  ┆                   ┆                 ┆ 3000             ┆         ┆           │
│ doi:10.1016/s0140 ┆                   ┆                 ┆ omid:br/06043969 ┆ 405139  ┆ 35        │
│ -6736(18)32278-5  ┆                   ┆                 ┆ 34               ┆         ┆           │
│ doi:10.1016/s0140 ┆                   ┆                 ┆ omid:br/06120394 ┆ 402578  ┆ 35        │
│ -6736(18)32279-7  ┆                   ┆                 ┆ 3001             ┆         ┆           │
│ doi:10.1016/s0140 ┆                   ┆                 ┆ omid:br/06043969 ┆ 402578  ┆ 35        │
│ -6736(18)32279-7  ┆                   ┆                 ┆ 35               ┆         ┆           │
│ doi:10.1016/s0140 ┆                   ┆                 ┆ omid:br/06120394 ┆ 402516  ┆ 35        │
│ -6736(18)32281-5  ┆                   ┆                 ┆ 2999             ┆         ┆           │
│ …                 ┆ …                 ┆ …               ┆ …                ┆ …       ┆ …         │
│ doi:10.12905/0380 ┆                   ┆                 ┆ omid:br/06804000 ┆ 292049  ┆ 35        │
│ .phyton55(2)2015- ┆                   ┆                 ┆ 244              ┆         ┆           │
│ 0193              ┆                   ┆                 ┆                  ┆         ┆           │
│ doi:10.12905/0380 ┆                   ┆                 ┆ omid:br/06803975 ┆ 292049  ┆ 35        │
│ .phyton55(2)2015- ┆                   ┆                 ┆ 023              ┆         ┆           │
│ 0193              ┆                   ┆                 ┆                  ┆         ┆           │
│ doi:10.12905/0380 ┆                   ┆                 ┆ omid:br/06404011 ┆ 292050  ┆ 35        │
│ .phyton55(2)2015- ┆                   ┆                 ┆ 317              ┆         ┆           │
│ 0201              ┆                   ┆                 ┆                  ┆         ┆           │
│ doi:10.12905/0380 ┆                   ┆                 ┆ omid:br/06240358 ┆ 292050  ┆ 35        │
│ .phyton55(2)2015- ┆                   ┆                 ┆ 8057             ┆         ┆           │
│ 0201              ┆                   ┆                 ┆                  ┆         ┆           │
│ doi:10.1007/jhep0 ┆ New Axion         ┆ report          ┆ omid:br/06190383 ┆ 700389  ┆ 35        │
│ 1(2019)113        ┆ Searches At       ┆                 ┆ 2621             ┆         ┆           │
│                   ┆ Flavor Factories  ┆                 ┆                  ┆         ┆           │
│ doi:10.1016/s0065 ┆ The Bacterial     ┆ book chapter    ┆ omid:br/06103694 ┆ 92438   ┆ 35        │
│ -2911(07)53001-8  ┆ Response To The   ┆                 ┆ 701              ┆         ┆           │
│                   ┆ Chalcogen         ┆                 ┆                  ┆         ┆           │
│                   ┆ Metalloids Se And ┆                 ┆                  ┆         ┆           │
│                   ┆ Te                ┆                 ┆                  ┆         ┆           │
│ doi:10.1016/s0074 ┆ Structural And    ┆ journal article ┆ omid:br/06504128 ┆ 84288   ┆ 41        │
│ -7696(06)53005-0  ┆ Immunocytochemica ┆                 ┆ 689              ┆         ┆           │
│                   ┆ l                 ┆                 ┆                  ┆         ┆           │
│                   ┆ Characterization  ┆                 ┆                  ┆         ┆           │
│                   ┆ Of Keratinization ┆                 ┆                  ┆         ┆           │
│                   ┆ In Vertebrate     ┆                 ┆                  ┆         ┆           │
│                   ┆ Epidermis And     ┆                 ┆                  ┆         ┆           │
│                   ┆ Epi…              ┆                 ┆                  ┆         ┆           │
│ doi:10.1016/s0076 ┆ Examining Ion     ┆ journal article ┆ omid:br/06250369 ┆ 666743  ┆ 41        │
│ -6879(09)66007-9  ┆ Channel           ┆                 ┆ 4462             ┆         ┆           │
│                   ┆ Properties Using  ┆                 ┆                  ┆         ┆           │
│                   ┆ Free-Energy       ┆                 ┆                  ┆         ┆           │
│                   ┆ Methods.          ┆                 ┆                  ┆         ┆           │
│ doi:10.1016/s0079 ┆ Implicit And      ┆ journal article ┆ omid:br/06804112 ┆ 74637   ┆ 41        │
│ -6123(06)56003-0  ┆ Explicit          ┆                 ┆ 214              ┆         ┆           │
│                   ┆ Categorization Of ┆                 ┆                  ┆         ┆           │
│                   ┆ Natural Scenes.   ┆                 ┆                  ┆         ┆           │
│ doi:10.1016/s0079 ┆ Functional Laser  ┆ journal article ┆ omid:br/06804112 ┆ 134111  ┆ 41        │
│ -6123(08)01111-4  ┆ Doppler Flowmetry ┆                 ┆ 785              ┆         ┆           │
│                   ┆ Of The Optic      ┆                 ┆                  ┆         ┆           │
│                   ┆ Nerve:            ┆                 ┆                  ┆         ┆           │
│                   ┆ Physiological     ┆                 ┆                  ┆         ┆           │
│                   ┆ Aspects And       ┆                 ┆                  ┆         ┆           │
│                   ┆ Clinical          ┆                 ┆                  ┆         ┆           │
│                   ┆ Applicatio…       ┆                 ┆                  ┆         ┆           │
│ doi:10.1016/s0079 ┆ Preface.          ┆ journal article ┆ omid:br/06903731 ┆ 369184  ┆ 42        │
│ -6123(18)30189-4  ┆                   ┆                 ┆ 137              ┆         ┆           │
│ doi:10.1016/s0091 ┆ Scanning Force    ┆ journal article ┆ omid:br/06260373 ┆ 673035  ┆ 41        │
│ -679x(02)68018-5  ┆ Microscopy        ┆                 ┆ 2535             ┆         ┆           │
│                   ┆ Studies On The    ┆                 ┆                  ┆         ┆           │
│                   ┆ Structure And     ┆                 ┆                  ┆         ┆           │
│                   ┆ Dynamics Of       ┆                 ┆                  ┆         ┆           │
│                   ┆ Single DNA        ┆                 ┆                  ┆         ┆           │
│                   ┆ Molecules.        ┆                 ┆                  ┆         ┆           │
└───────────────────┴───────────────────┴─────────────────┴──────────────────┴─────────┴───────────┘

In [ ]:
#remove the bunch of duplicates that have different types
lf_iim = lf_iim.join(to_drop.lazy(), on='omid', how='anti')

We can now merge all the entries that have the same external id and type. We will keep the first occurrence of each entry.

In [ ]:
lf_iim = lf_iim.unique(['iris_type', 'id'], keep='first', maintain_order=True)
print(lf_iim.filter(pl.col('id').is_duplicated()).select(pl.len()).collect(streaming=True).item(), 'duplicates remanining')

0 duplicates remanining

In [ ]:
lf_iim = lf_iim.unique('iris_id', keep='first')

In [ ]:
lf_iim.filter(pl.col('iris_id').is_duplicated()).sort('iris_id').collect(streaming=True)

shape: (0, 6)
┌─────┬───────┬──────┬──────┬─────────┬───────────┐
│ id  ┆ title ┆ type ┆ omid ┆ iris_id ┆ iris_type │
│ --- ┆ ---   ┆ ---  ┆ ---  ┆ ---     ┆ ---       │
│ str ┆ str   ┆ str  ┆ str  ┆ i64     ┆ i64       │
╞═════╪═══════╪══════╪══════╪═════════╪═══════════╡
└─────┴───────┴──────┴──────┴─────────┴───────────┘

In [ ]:
lf_iim.select(pl.len()).collect()

shape: (1, 1)
┌────────┐
│ len    │
│ ---    │
│ u32    │
╞════════╡
│ 111510 │
└────────┘

---

## Create III

In [7]:
import polars as pl
from pathlib import Path
from tqdm import tqdm
import dask.dataframe as dd
import os


lf_iim = pl.scan_parquet('../data/iris_in_meta/iris_in_meta.parquet')

omids_list = (
    lf_iim
    .select('omid')
    .collect(streaming=True)
)['omid'].to_list()

len(omids_list)

141591

In [16]:
index_path = Path('/run/media/leo/b9827f00-f8da-4458-bc94-97b28f1a0989/24356626.zip')
#index_path = Path('/run/media/leo/0EAE24EE1463E70C/opencitations/index_dump/24356626')
output_dir = Path("../data/iris_in_index")

In [25]:
str(index_path)

'/run/media/leo/b9827f00-f8da-4458-bc94-97b28f1a0989/24356626.zip'

In [27]:
# unzip the internal archives
if index_path.name.endswith(".zip"):
    extraction_dir = str(index_path).replace(".zip", "")
    with ZipFile(index_path, "r") as zip_ref:
        for member in tqdm(zip_ref.infolist(), desc='Extracting '):
            try:
                zip_ref.extract(member, extraction_dir)
            except ZipFile.error as e:
                pass

    index_path = extraction_dir
    print("Done!")

file_names = [
    Path(index_path) / Path(archive) for archive in os.listdir(index_path)
]

for archive in tqdm(file_names, desc='Processing archives'):
    zip_file = ZipFile(archive)

    csvs = ['zip://'+n for n in zip_file.namelist() if n.endswith('.csv')]

    ddf = dd.read_csv(csvs, storage_options={'fo': zip_file.filename}, usecols=['id', 'citing', 'cited'])
    ddf = ddf[ddf['cited'].isin(omids_list) | ddf['citing'].isin(omids_list)]
    ddf.to_parquet(output_dir / archive.stem, write_index=False)

Extracting 24356626.zip to /run/media/leo/b9827f00-f8da-4458-bc94-97b28f1a0989/24356626

  0%|          | 0/27 [00:44<?, ?it/s]

KeyboardInterrupt:

In [29]:
for archive in tqdm(file_names, desc='Processing archives'):
    zip_file = ZipFile(archive)

    csvs = ['zip://'+n for n in zip_file.namelist() if n.endswith('.csv')]

    ddf = dd.read_csv(csvs, storage_options={'fo': zip_file.filename}, usecols=['id', 'citing', 'cited'])
    ddf = ddf[ddf['cited'].isin(omids_list) | ddf['citing'].isin(omids_list)]
    ddf.to_parquet(output_dir / archive.stem, write_index=False)

Processing archives:   0%|          | 0/27 [01:46<?, ?it/s]

KeyboardInterrupt: